[agent]
  interval = "10s"
  flush_interval = "10s"
  omit_hostname = true

[global_tags]
  job = "debug_metrics"

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  container_name_include = ["inventory-api", "store-frontend"]
  perdevice_include = ["cpu"]
  total_include = ["cpu"]

# This copies the name into the BODY of the log message
# where dashes like 'inventory-api' are safe!
[[processors.converter]]
  [processors.converter.tags]
    string = ["container_name"]

[[outputs.loki]]
  domain = "http://loki:3100"
  endpoint = "/loki/api/v1/push"
  data_format = "logfmt"
  # Strictly whitelist only safe labels
  taginclude = ["job"]